version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.dev
    ports:
      - "${APP_PORT:-8088}:3000"  # gin 代理端口
    volumes:
      - .:/app:rw
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GO_ENV=development
    command: gin --appPort 8080 --port 3000 --immediate --path . --build ./cmd/server run main.go
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    ports:
      - "${DB_PORT:-3308}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    volumes:
      - ./deploy/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./mysql-config:/etc/mysql/conf.d
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:6.2-alpine
    ports:
      - "${REDIS_PORT:-6380}:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8089:8080"
    depends_on:
      - db

volumes:
  db_data: