version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: deploy/docker/Dockerfile
    ports:
      - "${APP_PORT:-8088}:8080"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: mysql:8.0
    ports:
      - "${DB_PORT:-3308}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./deploy/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - db_data:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    ports:
      - "${REDIS_PORT:-6380}:6379"

volumes:
  db_data: