# 使用官方 Go 鏡像
FROM golang:1.22.1

# 安裝 gin
RUN go install github.com/codegangsta/gin@latest

# 設置工作目錄
WORKDIR /app

# 複製 go mod 和 sum 文件
COPY go.mod go.sum ./

# 下載依賴
RUN go mod download

# 複製源代碼
COPY . .

# 設置 gin 的入口命令
CMD gin --appPort 8080 --port 3000 --build cmd/server --run main.go